<?php

/**
 * @file
 * Contains mod_perso.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mod_perso_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mod_perso module.
    case 'help.page.mod_perso':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mod_perso_theme() {
    $theme['mod_perso'] = array(
      'variables' => [
        'toto' => null,
        'tata' => null,
      ],
    );
    return $theme;
  }
