<?php
namespace Drupal\hello\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;


class HelloFormBlockcolor extends ConfigFormBase
{
  public function getFormId()
  {
    return 'hello_admin_form';
  }
  public function getEditableConfigNames()
  {
    return ['hello.config'];
  }
  public function buildForm(array $form, FormStateInterface $form_state)
  {
    $getconf = $this->config('hello.config')->get('color');

    $form['color_select'] = [
      '#type' => 'select',
      '#title' => $this->t('Select color'),
      '#options' => [
        'green-class'=> 'green',
        'orange-class'=> 'orange',
        'blue-class' => 'blue',
      ],
      '#default_value'=> $getconf
    ];
    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }
  public function submitForm(array &$form, FormStateInterface $form_state)
  {
    $this->config('hello.config')->set('color',$form_state->getValues('color_select'))->save();
    \Drupal::entityTypeManager()->getViewBuilder('block')->resetCache();
    
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }
}