<?php
function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match){
  switch ($route_name) {
    case 'help.page.hello':
      return'<p>Help page Hello module</p>';
      break;
    }
}

function hello_cron(){
  drupal_set_message(t('mon message'),'error');
}

/**
 * Implements hook_user_login().
 */
function hello_user_login($account){
  $name = $account->getDisplayName();
  drupal_set_message(t('Welcome dear @name',array('@name'=>$name)));
}

function hello_node_update(Drupal\Core\Entity\EntityInterface $entity)
{
  // Update the entity's entry in a fictional table of all entities.

  $query = \Drupal::database()->insert('hello_node_history');
  $query->fields([
    'nid' => $entity->id(),
    'update_time' => time(),
    'uid'=> \Drupal::currentUser()->id()
  ]);
  $query->execute();
}

function hello_page_attachements(array &$page){
  $page["#attached"]['library'][]='hello/blockcolor';
}

/**
 * Implements module_preprocess_HOOK().
 */
function hello_preprocess_block(&$vars){
  $config = \Drupal::config( 'hello.config');
  $color = $config->get('color');
  $vars['attributes']['class'][] = $color['color_select'];
}